# Generated by Django 4.0.4 on 2022-05-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='makePig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pig_name', models.CharField(max_length=20)),
                ('Pig_content', models.TextField()),
            ],
        ),
    ]
