# Generated by Django 4.0.4 on 2022-05-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pig_exchange_rate_pig_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='participants',
        ),
    ]
