# Generated by Django 4.0.4 on 2022-05-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_makepig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='makePig',
            new_name='Pig',
        ),
    ]
