# Generated by Django 4.0.4 on 2022-05-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pig_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='participants',
        ),
    ]
