# Generated by Django 4.0.4 on 2022-05-28 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_pig_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='exchange_rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pig',
            name='participants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pig_info', to='app.participants'),
            preserve_default=False,
        ),
    ]
