# Generated by Django 4.0.4 on 2022-05-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pig_pig_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='Pig_user',
        ),
    ]
